"""Generates a proof-of-concept script for a validated finding. When the
agent captured a structured replay recipe (poc_request), the script is a
genuinely runnable httpx call. Otherwise (XSS needs a browser, JWT forgery
needs custom headers) it falls back to a documentation-style script that
records exactly what was sent and what confirmed it, for manual reproduction.
"""
from __future__ import annotations

from typing import Any

HEADER = '''"""Proof-of-concept for a {agent_type} finding (id: {finding_id}).

Only run this against a target you are authorized to test.
Generated by Noctis -- see evidence/{finding_id}/request_response.txt for the
original captured request and response.
"""
'''


def generate_poc_script(agent_type: str, finding_id: str, result: dict[str, Any]) -> str:
    poc_request = result.get("poc_request")
    header = HEADER.format(agent_type=agent_type, finding_id=finding_id)

    if poc_request:
        return header + _runnable_script(poc_request, result)
    return header + _documentation_script(agent_type, result)


def _runnable_script(poc_request: dict[str, Any], result: dict[str, Any]) -> str:
    method = poc_request.get("method", "GET")
    url = poc_request.get("url", "")
    data = poc_request.get("data")
    content = poc_request.get("content")

    lines = ["import httpx", "", f"PAYLOAD = {result.get('payload', '')!r}", ""]
    if content is not None:
        lines.append(f"response = httpx.request({method!r}, {url!r}, content={content!r})")
    else:
        lines.append(f"response = httpx.request({method!r}, {url!r}, data={data!r})")
    lines += [
        'print(f"Status: {response.status_code}")',
        "print(response.text[:2000])",
        "",
        f"# Confirmed evidence: {result.get('evidence', '')}",
    ]
    return "\n".join(lines) + "\n"


def _documentation_script(agent_type: str, result: dict[str, Any]) -> str:
    lines = [
        f"# Agent type: {agent_type}",
        f"# Payload: {result.get('payload', '')}",
        "#",
        "# Original request:",
    ]
    for line in result.get("request", "").splitlines():
        lines.append(f"# {line}")
    lines += [
        "#",
        f"# Confirmed evidence: {result.get('evidence', '')}",
        "#",
        "# This finding needs more than a plain HTTP request to reproduce",
        "# (a real browser for XSS, custom headers for forged auth tokens, etc) --",
        "# see request_response.txt in this finding's evidence folder for the",
        "# full captured request and response, and reproduce manually or adapt",
        "# this script with the noctis.agents module used to confirm it.",
    ]
    return "\n".join(lines) + "\n"
